apiVersion: apps/v1
kind: Deployment
metadata:
  name: rahul-obts
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-myapp
  template:
    metadata:
      labels:
        app: app-myapp
    spec:
      containers:
      - name: my-app-container
        image: rahul1516/cpbts-app:latest
        ports:
        - containerPort: 4545
        env:
        - name: MONGODB_URI
          value: mongodb://mongo-service:27017/bank_transaction_system
      - name: mongo-container
        image: mongo:latest
        ports:
          - containerPort: 27017
